export const ETHERS_INDEXER_TASK_NAME = 'ETHERS_INDEXER_TASK_NAME'
export const ETHERS_INDEXER_TASK_ARGS = 'ETHERS_INDEXER_TASK_ARGS'
export const ETHERS_INDEXER_INSTANCES = 'ETHERS_INDEXER_INSTANCES'
